@startuml

actor User

' Future Expansions
User --> (Banking Integration) : <<extend>>
User --> (IA Suggestions) : <<extend>>
User --> (Alerts) : <<extend>>
User --> (Real Time Quotes) : <<include>>

@enduml
